let name_Mangla='Mangla'
let name_Chashma='Chashma'
let name_Tarbela='Tarbela'
let name_Thein='Thein'
let name_Pong='Pong'
let name_Bhakra='Bhakra'
let val_Tarbela='1456.59'
let val_Mangla='1143.60'
let val_Chashma='648.50'
let lastYearLevel_Tarbela=1.63
let lastYearLevel_Mangla=3.12
let lastYearLevel_Chashma=24.76
let avg5YearLevel_Tarbela=5.07
let avg5YearLevel_Mangla=6.82
let avg5YearLevel_Chashma=42.44
let variation5Year_Tarbela=333
let variation5Year_Mangla=196
let variation5Year_Chashma=116
let variation5YearArrow_Tarbela='▲'
let variation5YearArrow_Mangla='▲'
let variation5YearArrow_Chashma='▲'
let variation5YearTrend_Tarbela='increase'
let variation5YearTrend_Mangla='increase'
let variation5YearTrend_Chashma='increase'
let val_Thein='1685.68'
let val_Pong='1330.09'
let val_Bhakra='1581.09'
let fillPercentage_Tarbela = 21.95
let fillPercentage_Mangla= 20.15
let fillPercentage_Chashma = 91.64
let fillPercentage_Thein= 53.69
let fillPercentage_Pong= 39.20
let fillPercentage_Bhakra= 37.17
let fillPercentage_Thein_last_year= 33.58
let fillPercentage_Pong_last_year= 13.29
let fillPercentage_Bhakra_last_year= 21.14
let fillPercentage_Thein_normal= 38.93
let fillPercentage_Pong_normal= 27.35
let fillPercentage_Bhakra_normal= 26.40