let name_Mangla='Mangla'
let name_Chashma='Chashma'
let name_Tarbela='Tarbela'
let name_Thein='Thein'
let name_Pong='Pong'
let name_Bhakra='Bhakra'
let val_Tarbela='1453.30'
let val_Mangla='1170.60'
let val_Chashma='644.90'
let lastYearLevel_Tarbela=29.05
let lastYearLevel_Mangla=31.57
let lastYearLevel_Chashma=42.44
let avg5YearLevel_Tarbela=14.21
let avg5YearLevel_Mangla=21.29
let avg5YearLevel_Chashma=43.73
let variation5Year_Tarbela=41
let variation5Year_Mangla=69
let variation5Year_Chashma=2
let variation5YearArrow_Tarbela='▲'
let variation5YearArrow_Mangla='▲'
let variation5YearArrow_Chashma='▲'
let variation5YearTrend_Tarbela='increase'
let variation5YearTrend_Mangla='increase'
let variation5YearTrend_Chashma='increase'
let val_Thein='1685.68'
let val_Pong='1330.09'
let val_Bhakra='1581.09'
let fillPercentage_Tarbela = 20.04
let fillPercentage_Mangla= 35.88
let fillPercentage_Chashma = 44.37
let fillPercentage_Thein= 53.69
let fillPercentage_Pong= 39.20
let fillPercentage_Bhakra= 37.17
let fillPercentage_Thein_last_year= 33.58
let fillPercentage_Pong_last_year= 13.29
let fillPercentage_Bhakra_last_year= 21.14
let fillPercentage_Thein_normal= 38.93
let fillPercentage_Pong_normal= 27.35
let fillPercentage_Bhakra_normal= 26.40