var name_Mangla='Mangla'
var name_Chashma='Chashma'
var name_Tarbela='Tarbela'
var name_Thein='Thein'
var name_Pong='Pong'
var name_Bhakra='Bhakra'
var res_lvl_value_Tarbela='1550.00'
var res_lvl_value_Mangla='1218.65'
var res_lvl_value_Chashma='648.50'
var lastYearLevel_Tarbela=100.00
var lastYearLevel_Mangla=79.46
var lastYearLevel_Chashma=68.17
var avg5YearLevel_Tarbela=100.00
var avg5YearLevel_Mangla=72.19
var avg5YearLevel_Chashma=54.98
var variation5Year_Tarbela=-3
var variation5Year_Mangla=5
var variation5Year_Chashma=67
var variation5YearArrow_Tarbela='▼'
var variation5YearArrow_Mangla='▲'
var variation5YearArrow_Chashma='▲'
var variation5YearTrend_Tarbela='decrease'
var variation5YearTrend_Mangla='increase'
var variation5YearTrend_Chashma='increase'
var res_lvl_value_Thein='1689'
var res_lvl_value_Pong='1361'
var res_lvl_value_Bhakra='1627'
var fillPercentage_Tarbela = 100.00
var fillPercentage_Mangla= 75.61
var fillPercentage_Chashma = 91.64
var fillPercentage_Thein= 58.60
var fillPercentage_Pong= 61.94
var fillPercentage_Bhakra= 53.87
var fillPercentage_Thein_last_year= 83.58
var fillPercentage_Pong_last_year= 85.83
var fillPercentage_Bhakra_last_year= 80.09
var fillPercentage_Thein_5year_normal= 66.83
var fillPercentage_Pong_5year_normal= 69.48
var fillPercentage_Bhakra_5year_normal= 70.07