#!/bin/bash
set -euo pipefail

# ──────────────────────────────────────────────────────────────────
# Hydro Analytics — First-Time Deployment on Ubuntu VM
# Run this script ONCE on the Ubuntu VM (172.18.7.35)
# ──────────────────────────────────────────────────────────────────

DEPLOY_DIR="/opt/hydroanalytics"
REPO_URL="git@github.com:Ibrahom1/Hydro-analytics-Portal.git"

echo "═══════════════════════════════════════════════════════════"
echo "  Hydro Analytics — Podman Pod Deployment Setup"
echo "═══════════════════════════════════════════════════════════"

# ── Port Conflict Detection (mirrors run_on_other_pc.bat FindFreePort) ──
find_free_port() {
    local port=$1
    local label=$2
    while ss -tlnH 2>/dev/null | grep -qE ":${port}\b"; do
        echo "  ⚠  Port $port ($label) is already in use. Trying $((port + 1))..."
        port=$((port + 1))
    done
    echo "$port"
}

echo ""
echo "[0/10] Checking for port conflicts..."
HYDRO_PROXY_PORT=$(find_free_port 8000 "Reverse Proxy")
HYDRO_DASHBOARD_PORT=$(find_free_port 5000 "Dashboard API")
HYDRO_GIS_PORT=$(find_free_port 8001 "GIS Uploader")
HYDRO_UI_PORT=$(find_free_port 5504 "Frontend UI")

echo ""
echo "  ✓ Selected Ports:"
echo "    Reverse Proxy (cloudflared target): $HYDRO_PROXY_PORT"
echo "    Dashboard Flask Backend:            $HYDRO_DASHBOARD_PORT"
echo "    GIS Uploader FastAPI:               $HYDRO_GIS_PORT"
echo "    Frontend UI (Nginx):                $HYDRO_UI_PORT"
echo ""

# 1. Install Podman + podman-compose
echo "[1/10] Installing Podman & dependencies..."
sudo apt-get update
sudo apt-get install -y podman podman-compose git curl

# 2. Set timezone
echo ""
echo "[2/10] Setting timezone to Asia/Karachi..."
sudo timedatectl set-timezone Asia/Karachi

# 3. Create directory structure
echo ""
echo "[3/10] Creating directory structure at $DEPLOY_DIR..."
sudo mkdir -p "$DEPLOY_DIR"/{app,data/historical_river_data,data/meteoblue_cache}
sudo mkdir -p "$DEPLOY_DIR/res_storages/Historical Daily Storages"
sudo mkdir -p "$DEPLOY_DIR/res_kp/Historical KP Reports"
sudo mkdir -p "$DEPLOY_DIR"/{script,ffd_fetch,env,wwebjs_auth}
sudo mkdir -p "$DEPLOY_DIR"/git_config/.ssh
sudo mkdir -p "$DEPLOY_DIR"/{logs/whatsapp,scripts}

# 4. Clone repository
echo ""
echo "[4/10] Cloning repository..."
if [ -d "$DEPLOY_DIR/app/.git" ]; then
    echo "Repository already exists, pulling latest..."
    cd "$DEPLOY_DIR/app" && sudo git pull
else
    sudo git clone "$REPO_URL" "$DEPLOY_DIR/app"
fi

# 5. Seed persistent volumes from the repo clone
echo ""
echo "[5/10] Seeding persistent data volumes..."
sudo cp -rn "$DEPLOY_DIR/app/data/"* "$DEPLOY_DIR/data/" 2>/dev/null || true
sudo cp -rn "$DEPLOY_DIR/app/res_storages/"* "$DEPLOY_DIR/res_storages/" 2>/dev/null || true
sudo cp -rn "$DEPLOY_DIR/app/res_kp/"* "$DEPLOY_DIR/res_kp/" 2>/dev/null || true
sudo cp -n "$DEPLOY_DIR/app/script/ft_and_percentage.js" "$DEPLOY_DIR/script/" 2>/dev/null || true
sudo cp -n "$DEPLOY_DIR/app/FFD_other_gauge_fetch/latest_all_gauges.json" "$DEPLOY_DIR/ffd_fetch/" 2>/dev/null || true
sudo cp -rn "$DEPLOY_DIR/app/env/"* "$DEPLOY_DIR/env/" 2>/dev/null || true

# 6. Setup Git config for WhatsApp bot pushes
echo ""
echo "[6/10] Configuring Git for container pushes..."
cat > "$DEPLOY_DIR/git_config/.gitconfig" << 'EOF'
[user]
    name = Hydro Analytics Bot
    email = bot@hydroanalytics.local
[safe]
    directory = /app
EOF

echo ""
echo "  ⚠️  IMPORTANT: Copy your SSH private key to:"
echo "     $DEPLOY_DIR/git_config/.ssh/id_rsa"
echo "     (or id_ed25519 — whichever you use for GitHub)"
echo ""
echo "  Then run: chmod 600 $DEPLOY_DIR/git_config/.ssh/id_*"
echo "  And add github.com to known_hosts:"
echo "     ssh-keyscan github.com >> $DEPLOY_DIR/git_config/.ssh/known_hosts"

# 7. Write .env.ports file (used by podman-compose for port bindings)
echo ""
echo "[7/10] Writing resolved port configuration..."
cat > "$DEPLOY_DIR/.env.ports" << EOF
# Auto-generated by deploy.sh at $(date '+%Y-%m-%d %H:%M:%S %Z')
# Re-run deploy.sh or find_free_ports.sh to regenerate
HYDRO_PROXY_PORT=$HYDRO_PROXY_PORT
HYDRO_DASHBOARD_PORT=$HYDRO_DASHBOARD_PORT
HYDRO_GIS_PORT=$HYDRO_GIS_PORT
HYDRO_UI_PORT=$HYDRO_UI_PORT
EOF
echo "  Written to: $DEPLOY_DIR/.env.ports"

# Also export for current session
export HYDRO_PROXY_PORT HYDRO_DASHBOARD_PORT HYDRO_GIS_PORT HYDRO_UI_PORT

# 8. Copy & install management scripts
echo ""
echo "[8/10] Installing management scripts..."
sudo cp "$DEPLOY_DIR/app/scripts/"*.sh "$DEPLOY_DIR/scripts/" 2>/dev/null || true
sudo chmod +x "$DEPLOY_DIR/scripts/"*.sh

# 9. Build container images
echo ""
echo "[9/10] Building container images (this may take 5-10 minutes)..."
cd "$DEPLOY_DIR/app"
sudo podman build -f docker/Dockerfile.python -t hydro-python:latest .
sudo podman build -f docker/Dockerfile.whatsapp -t hydro-whatsapp:latest .
sudo podman build -f docker/Dockerfile.frontend -t hydro-frontend:latest .

# 10. Start the pod (with resolved ports)
echo ""
echo "[10/10] Starting Hydro Analytics pod..."
cd "$DEPLOY_DIR/app"

# Source .env.ports so podman-compose picks up HYDRO_*_PORT variables
set -a
source "$DEPLOY_DIR/.env.ports"
set +a

sudo -E podman-compose -f docker/podman-compose.yml up -d

# 11. Setup WhatsApp bot cron (twice daily: 8:55 AM & 8:55 PM Karachi)
echo ""
echo "Setting up WhatsApp bot cron schedule..."
(sudo crontab -l 2>/dev/null || true; echo "55 8,20 * * * $DEPLOY_DIR/scripts/whatsapp-cron.sh") \
    | sort -u | sudo crontab -

echo ""
echo "═══════════════════════════════════════════════════════════"
echo "  ✅ DEPLOYMENT COMPLETE!"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "  Services running (ports auto-resolved from .env.ports):"
echo "  ┌─────────────────────────────────────────────────────────┐"
echo "  │ Reverse Proxy    → http://172.18.7.35:$HYDRO_PROXY_PORT          │"
echo "  │ Dashboard API    → http://172.18.7.35:$HYDRO_DASHBOARD_PORT/api/health│"
echo "  │ GIS Uploader     → http://172.18.7.35:$HYDRO_GIS_PORT          │"
echo "  │ Frontend UI      → http://172.18.7.35:$HYDRO_UI_PORT          │"
echo "  │ Cloudflare Tunnel→ podman logs hydro-cloudflared      │"
echo "  │ Tailscale        → http://<tailscale-ip>:$HYDRO_PROXY_PORT       │"
echo "  │ WhatsApp Bot     → Cron: 8:55 AM & 8:55 PM daily     │"
echo "  └─────────────────────────────────────────────────────────┘"
echo ""
echo "  Port config saved to: $DEPLOY_DIR/.env.ports"
echo ""
echo "  📱 NEXT STEP — Scan WhatsApp QR code (one-time only):"
echo ""
echo "  sudo podman run -it --rm \\"
echo "    -v /opt/hydroanalytics/wwebjs_auth:/app/whatsapp_bot/.wwebjs_auth \\"
echo "    -e PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium \\"
echo "    --shm-size=512m \\"
echo "    localhost/hydro-whatsapp:latest node bot.js --auth-only"
echo ""
echo "  🔑 SSH KEY — Copy your GitHub SSH key:"
echo "  scp ~/.ssh/id_rsa user@172.18.7.35:$DEPLOY_DIR/git_config/.ssh/"
echo "  ssh user@172.18.7.35 'chmod 600 $DEPLOY_DIR/git_config/.ssh/id_rsa'"
echo "  ssh user@172.18.7.35 'ssh-keyscan github.com >> $DEPLOY_DIR/git_config/.ssh/known_hosts'"
echo ""
