#!/bin/bash
# ──────────────────────────────────────────────────────────────────
# find_free_ports.sh — Port conflict detection & resolution
#
# Checks if the desired ports are available on the host.
# If a port is already in use by another service on the VM,
# it increments until a free port is found.
#
# Writes results to /opt/hydroanalytics/.env.ports which is
# sourced by podman-compose, deploy.sh, and whatsapp-cron.sh.
#
# Mirrors the FindFreePort logic from run_on_other_pc.bat.
# ──────────────────────────────────────────────────────────────────

DEPLOY_DIR="${DEPLOY_DIR:-/opt/hydroanalytics}"
ENV_PORTS_FILE="$DEPLOY_DIR/.env.ports"

# ── find_free_port <desired_port> ─────────────────────────────────
# Returns the first available port starting from <desired_port>.
# A port is "in use" if ss/netstat shows it in LISTEN state.
find_free_port() {
    local port=$1
    while true; do
        if ss -tlnH 2>/dev/null | grep -qE ":${port}\b"; then
            echo "  ⚠  Port $port is already in use. Trying $((port + 1))..." >&2
            port=$((port + 1))
        else
            echo "$port"
            return 0
        fi
    done
}

echo "─────────────────────────────────────────────────────────"
echo "  Port Conflict Detection"
echo "─────────────────────────────────────────────────────────"

# Desired (default) ports — same as the Windows run_on_other_pc.bat
PROXY_PORT=$(find_free_port 8000)
DASHBOARD_PORT=$(find_free_port 5000)
GIS_PORT=$(find_free_port 8001)
UI_PORT=$(find_free_port 5504)

echo ""
echo "  Resolved Ports:"
echo "    Reverse Proxy (HYDRO_PROXY_PORT):       $PROXY_PORT"
echo "    Dashboard API (HYDRO_DASHBOARD_PORT):   $DASHBOARD_PORT"
echo "    GIS Uploader  (HYDRO_GIS_PORT):         $GIS_PORT"
echo "    Frontend UI   (HYDRO_UI_PORT):          $UI_PORT"
echo ""

# Write .env.ports file (sourced by podman-compose and scripts)
cat > "$ENV_PORTS_FILE" << EOF
# Auto-generated by find_free_ports.sh at $(date '+%Y-%m-%d %H:%M:%S')
# Do not edit manually — re-run find_free_ports.sh to regenerate
HYDRO_PROXY_PORT=$PROXY_PORT
HYDRO_DASHBOARD_PORT=$DASHBOARD_PORT
HYDRO_GIS_PORT=$GIS_PORT
HYDRO_UI_PORT=$UI_PORT
EOF

echo "  Written to: $ENV_PORTS_FILE"
echo "─────────────────────────────────────────────────────────"
